  
name: Deploy to Lambda
on:
  push:
    tags: 
      - v*

jobs:
  deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 12.x
      - name: npm build
        run: npm i
        working-directory: ./src/
      - name: zip archive
        run: |
          zip -r deploy.zip .
        working-directory: ./src/        
      - uses: appleboy/lambda-action@v0.0.2
        with:
          # AWS ACCESS KEY
          aws_access_key_id: ${{ secrets.S3_ACCESS_KEY_ID }}
          # AWS SECRET KEY
          aws_secret_access_key: ${{ secrets.S3_SECRET_ACCESS_KEY }}
          # AWS Region
          aws_region: ap-northeast-1
          # AWS lambda function name
          function_name: ${{ secrets.LAMBDA_FUNCTION_NAME }}
          # AWS lambda zip file
          zip_file: src/deploy.zip
